version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nishad
      POSTGRES_DB: isam
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    image: nishadshanid/ecommerce-isam:1.0
    ports:
      - "3000:3000"
    environment:
      DB_KEY: "host=db user=postgres password=nishad dbname=isam port=5432 sslmode=disable"
    depends_on:
      - db
    volumes:
      - ./template:/app/template


